class LapMegaSpecsSpider < MegaSpecsSpider
  def selectSpecs()
    [
      "Processor Type",
      "Processor Speed",
      "Hard drive size",
      "Installed RAM",
      "Screen size",
      "Operating system (Primary)",
      "Processor Type",
      "Processor Model",
      "Processor Speed",
      "Max Turbo Frequency",
      "Processor Bits",
      "Processor Threads",
      "No of Cores",
      "L2 cache",
      "L3 cache",
      "Bus speed",
      "Chipset",
      "Number of memry slots",
      "Installed RAM",
      "Maximum memory",
      "Type of memory",
      "Hard drive size",
      "Hard drive speed",
      "Optical Drive",
      "Type of optical drive",
      "Internal/External",
      "Type of harddrive",
      "Card Reader",
      "Type of memory cards",
      "SSD",
      "Number of SSDs",
      "SSD size",
      "Dedicated graphics",
      "Graphics memory",
      "Type of graphics memory",
      "Switchable graphics",
      "Graphics processor",
      "Maximum shared graphics memory",
      "Aspect ratio",
      "Backlight",
      "Screen size",
      "Screen surface",
      "Screen resolution",
      "Touchscreen",
      "Colors",
      "Dimensions (WxHxD)",
      "Weight",
      "Fingerprint Reader",
      "Numeric keyboard",
      "Backlit keyboard",
      "3G",
      "EDGE",
      "Bluetooth",
      "Type of bluetooth",
      "LAN",
      "Modem",
      "Wireless/Wifi",
      "Infrared",
      "DVI out",
      "eSATA",
      "Firewire",
      "Headphone output",
      "Microphone input",
      "Parallel port",
      "S/PDIF out",
      "Serial port",
      "TV-out",
      "USB",
      "USB 2.0",
      "USB 3.0",
      "USB Ports (Total)",
      "HDMI",
      "Number of outputs",
      "HDMI version",
      "VGA Output",
      "Battery life",
      "Battery type",
      "No of cells",
      "Camera",
      "No. of effective pixels",
      "Remote Control",
      "32/64-bit OS",
      "Operating system (Primary)"
    ]
  end
end