class MobiMegaSpecsSpider < MegaSpecsSpider
  def selectSpecs()
    [
        "Camera Pixels",
        "Touchscreen",
        "Battery capacity",
        "4G LTE",
        "Screen size",
        "Operating system",
        "Display technology",
        "Display",
        "Number of colours",
        "Scratch resistant display",
        "Screen resolution",
        "Screen size",
        "Pixel density",
        "Touchscreen",
        "Simultaneous touch points",
        "Dual screens",
        "Internal storage space",
        "Memory card readers",
        "Compatible memory cards",
        "Maximum amount of memory",
        "ROM memory",
        "Built-in camera",
        "Auto focus",
        "Built-in flash",
        "Digital zoom (still image)",
        "Camera Pixels",
        "Maximum resolution (still)",
        "Number of cameras",
        "Resolution 2nd camera",
        "Optical zoom",
        "Video recorder",
        "Digital zoom (video)",
        "Maximum numbers of fps when recording",
        "Torch/Lamp",
        "Graphics processor",
        "Graphics processor type",
        "Processor core type",
        "Processor speed",
        "RAM",
        "Memory quantity",
        "SoC (System on Chip)",
        "CPU type",
        "2G (GSM)",
        "Stand-by time (2G)",
        "Talk time (2G)",
        "EDGE",
        "GPRS",
        "3G (UMTS)",
        "Stand-by time (3G)",
        "Talk time (3G)",
        "HSPA",
        "HSUPA: Speed (down)",
        "HSDPA: Speed (up)",
        "4G LTE",
        "4G: Speed (down/up)",
        "Stand by time (4G)",
        "Talk time (4G)",
        "Bluetooth",
        "Bluetooth profile",
        "Version",
        "Built-in navigation system",
        "Type of GPS",
        "Integrated geotagging",
        "IR",
        "Support for IP telephony",
        "Supports NFC",
        "Wireless network (Wi-Fi)",
        "Supports media sharing",
        "Type",
        "Colour",
        "Sliding",
        "Physical keyboard/numpad",
        "Features (detail)",
        "Shock resistant",
        "Dual SIM card support",
        "Voice dialing",
        "Water resistant",
        "Supports wireless charging",
        "Built-in wireless charging",
        "DLNA certified",
        "OpenGL ES",
        "Java",
        "3.5mm headphone output",
        "Type of connection",
        "USB",
        "Charging via USB",
        "Type of USB connector",
        "USB version",
        "Dimensions (WxHxD)",
        "Weight",
        "Battery capacity",
        "Exchangeable battery",
        "Operating system",
        "Release year"
    ]
  end
end