class TabMegaSpecsSpider < MegaSpecsSpider
  def selectSpecs()
    [
      "Operating system",
      "Built-in camera",
      "3G (UMTS)",
      "Wireless network",
      "VGA out",
      "Screen size",
      "Buttons",
      "Operating system",
      "Built-in microphone",
      "Built-in speakers",
      "Built-in camera",
      "Auto focus",
      "Built-in flash",
      "Flash type",
      "Digital zoom (still image)",
      "Efficient numbers of pixels",
      "Maximum resolution (still)",
      "Number of cameras",
      "Resolution 2nd Camera",
      "Video recorder",
      "Digital zoom (video)",
      "Maximum number of fps when recording",
      "Maximum resolution (video)",
      "Lamp",
      "3G (UMTS)",
      "HSPA",
      "Speed (down)",
      "Speed (up)",
      "Bluetooth",
      "Bluetooth profile",
      "Version",
      "Built-in FM transmitter",
      "EDGE",
      "Frequency band",
      "GPRS",
      "IR",
      "Network connection",
      "Supports NFC",
      "Support for IP technology",
      "Web and email functions",
      "Wireless network",
      "Support media sharing",
      "Type",
      "DLNA certified",
      "Type",
      "Dockable",
      "HDMI",
      "Headphone output",
      "Microphone input",
      "S/PDIF out",
      "USB",
      "Charging via USB",
      "USB 2.0 ports",
      "USB 3.0 ports",
      "USB ports (total)",
      "VGA out",
      "FM radio",
      "Supported audio files",
      "Supported image files",
      "Supported video files",
      "Colour",
      "Dimensions (WxHxD)",
      "Weight",
      "Built in GPS navigation",
      "Integrated geotagging",
      "Type of GPS",
      "Built-in internet services",
      "Backlight",
      "Pivot function",
      "Type",
      "Scratch resistant display",
      "Screen resolution",
      "Screen size",
      "Simultaneous touch points",
      "Type of technology",
      "Memory Speed",
      "RAM size",
      "Type of memory",
      "Battery capacity",
      "Battery life",
      "battery type",
      "Graphics processor",
      "Graphics processor type",
      "Processor core type",
      "Processor speed",
      "SoC (System on Chip)",
      "Type of processor",
      "Internal storage space",
      "Internal storage space (type)",
      "Memory card readers",
      "Compatible memory cards",
      "Including memory card",
      "Maximum amount of memory",
      "release year",
      "Product page",
      "Operating system",
      "Built-in camera",
      "3G (UMTS)",
      "Screen size",
      "Operating system",
      "Built-in camera",
      "Auto focus",
      "Built-in flash",
      "Number of cameras",
      "Video recorder",
      "Digital zoom (video)",
      "3G (UMTS)",
      "HSPA",
      "Bluetooth",
      "Bluetooth profile",
      "Version",
      "EDGE",
      "Type",
      "DLNA certified",
      "USB",
      "Charging via USB",
      "Colour",
      "Dimensions (WxHxD)",
      "Weight",
      "Integrated geotagging",
      "Type of GPS",
      "Scratch resistant display",
      "Screen resolution",
      "Screen size",
      "Simultaneous touch points",
      "Battery capacity",
      "Graphics processor",
      "Processor core type",
      "Processor speed",
      "SoC (System on Chip)",
      "Internal storage space",
      "Memory card readers"
    ]
  end
end