require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe UsedProductsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # UsedProduct. As you add validations to UsedProduct, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UsedProductsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all used_products as @used_products" do
      used_product = UsedProduct.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:used_products)).to eq([used_product])
    end
  end

  describe "GET #show" do
    it "assigns the requested used_product as @used_product" do
      used_product = UsedProduct.create! valid_attributes
      get :show, {:id => used_product.to_param}, valid_session
      expect(assigns(:used_product)).to eq(used_product)
    end
  end

  describe "GET #new" do
    it "assigns a new used_product as @used_product" do
      get :new, {}, valid_session
      expect(assigns(:used_product)).to be_a_new(UsedProduct)
    end
  end

  describe "GET #edit" do
    it "assigns the requested used_product as @used_product" do
      used_product = UsedProduct.create! valid_attributes
      get :edit, {:id => used_product.to_param}, valid_session
      expect(assigns(:used_product)).to eq(used_product)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new UsedProduct" do
        expect {
          post :create, {:used_product => valid_attributes}, valid_session
        }.to change(UsedProduct, :count).by(1)
      end

      it "assigns a newly created used_product as @used_product" do
        post :create, {:used_product => valid_attributes}, valid_session
        expect(assigns(:used_product)).to be_a(UsedProduct)
        expect(assigns(:used_product)).to be_persisted
      end

      it "redirects to the created used_product" do
        post :create, {:used_product => valid_attributes}, valid_session
        expect(response).to redirect_to(UsedProduct.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved used_product as @used_product" do
        post :create, {:used_product => invalid_attributes}, valid_session
        expect(assigns(:used_product)).to be_a_new(UsedProduct)
      end

      it "re-renders the 'new' template" do
        post :create, {:used_product => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested used_product" do
        used_product = UsedProduct.create! valid_attributes
        put :update, {:id => used_product.to_param, :used_product => new_attributes}, valid_session
        used_product.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested used_product as @used_product" do
        used_product = UsedProduct.create! valid_attributes
        put :update, {:id => used_product.to_param, :used_product => valid_attributes}, valid_session
        expect(assigns(:used_product)).to eq(used_product)
      end

      it "redirects to the used_product" do
        used_product = UsedProduct.create! valid_attributes
        put :update, {:id => used_product.to_param, :used_product => valid_attributes}, valid_session
        expect(response).to redirect_to(used_product)
      end
    end

    context "with invalid params" do
      it "assigns the used_product as @used_product" do
        used_product = UsedProduct.create! valid_attributes
        put :update, {:id => used_product.to_param, :used_product => invalid_attributes}, valid_session
        expect(assigns(:used_product)).to eq(used_product)
      end

      it "re-renders the 'edit' template" do
        used_product = UsedProduct.create! valid_attributes
        put :update, {:id => used_product.to_param, :used_product => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested used_product" do
      used_product = UsedProduct.create! valid_attributes
      expect {
        delete :destroy, {:id => used_product.to_param}, valid_session
      }.to change(UsedProduct, :count).by(-1)
    end

    it "redirects to the used_products list" do
      used_product = UsedProduct.create! valid_attributes
      delete :destroy, {:id => used_product.to_param}, valid_session
      expect(response).to redirect_to(used_products_url)
    end
  end

end
